site_name: Starling Bearing Docs

dev_addr: 127.0.0.1:8888

theme:
  name: material
  locale: en
  palette:
    scheme: starling
    # primary: light blue
  logo: assets/logo.png
  favicon: assets/images/favicon.png
  # features:
  #   - navigation.tabs

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX
  social:
    - icon: fontawesome/solid/globe 
      link: https://www.starling.associates
    - icon: fontawesome/brands/github 
      link: https://github.com/starling-cloud
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/starling-associates/
    - icon: fontawesome/brands/instagram 
      link: https://instagram.com/starling.cloud/
    - icon: fontawesome/brands/facebook 
      link: https://www.facebook.com/starlingclouds/


copyright: Copyright &copy; 2023 Starling Associates

hide:
  - footer

pages:
- Getting Started:
    - 'Introduction': 'index.md'
- Glossary: 'glossary.md'
- License: 'license.md'
- Privacy Policy: 'privacy.md'

